package:
  name: evergreen
  version: 1.0.0

source:
  - url: https://bitbucket.org/genomicepidemiology/evergreen/get/1.0.0.tar.gz

build:
  number: 0
  noarch: python
  script: conda env create --file evergreen/scripts/environment.yml

requirements:
  build:
    - Anaconda Python 2.7
    - Joblib package 0.13+
    - ETE3 package 3.0+
    - KMA 1.3.28
    - IQ-tree 1.6
    - PHYLIP package 3.697
  host:
    - Anaconda Python 2.7
    - Joblib package 0.13+
    - ETE3 package 3.0+
    - KMA 1.3.28
    - IQ-tree 1.6
    - PHYLIP package 3.697

test:
  commands:
    - parallel_snp_pipeline.py -h | grep parallel_snp_pipeline.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0