package:
  name: evergreen
  version: 3.5.5

source:
   url: https://github.com/Kollurisatya/coding_practice/archive/refs/tags/v3.5.5.tar.gz

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - wget
    - python=2.7
    - kma=1.4.9
    - numpy=1.15
    - scipy
  run:
    - wget
    - python=2.7
    - kma=1.4.9
    - numpy=1.15
test:
  commands:
    - parallel_snp_pipeline.py | parallel_snp_pipeline.py >/dev/null
about:
  home: https://github.com/KolluriSatya/coding_practice/tree/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0