package:
  name: mintyper
  version: 0.1.0

source:
  url: https://bitbucket.org/genomicepidemiology/mintyper

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.6
    - pip
    - kma >=1.4.9
    - ccphylo >=0.8.2
  run:
    - python >=3.6
    - pip
    - kma >=1.4.9
    - ccphylo >=0.8.2
about:
  home: https://github.com/genomicepidemiology/mintyper
  summary: 'mintyper test.'
  license: Apache-2.0