package:
  name: evergreen
  version: 1.0.0

source:
  - url: https://bitbucket.org/genomicepidemiology/evergreen/get/1.0.0.tar.gz

build:
  number: 0
  noarch: python
  script: conda env create --file evergreen/scripts/environment.yml

requirements:
  host:
    - python=2.7
    - scipy
    - numpy=1.15
    - ete3
    - joblib

  run:
    - python=2.7
    - scipy
    - numpy=1.15
    - ete3
    - joblib
test:
  commands:
    - parallel_snp_pipeline.py -h | grep parallel_snp_pipeline.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0