package:
  name: evergreen
  version: 1.0.0

source:
   url: https://github.com/KolluriSatya/coding_practice/blob/evergreen

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - mamba
    - wget
    - python=2.7
    - kma=1.4.9
  run:
    - mamba
    - wget
    - python=2.7
    - kma=1.4.9
about:
  home: https://github.com/KolluriSatya/coding_practice/tree/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0