package:
  name: flankophile
  version: 0.2.8

source:
  url: https://github.com/KolluriSatya/coding_practice/archive/refs/v0.2.8.tar.gz

build:
  number: 0
  noarch: generic
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6
  run:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6
test:
  commands:
    snakemake --use-conda --cores <number of cores> | grep snakemake --use-conda --cores <number of cores>  >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/flankophile
  summary: 'flankophile test.'
  license: Apache-2.0