package:
  name: tabulate
  version: 0.9.0
source:
  url: https://files.pythonhosted.org/packages/ec/fe/802052aecb21e3797b8f7902564ab6ea0d60ff8ca23952079064155d1ae1/tabulate-0.9.0.tar.gz

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython

about:
  home: https://bitbucket.org/genomicepidemiology/tabulate
  summary: 'tabulate test.'
  license: Apache-2.0
