package:
  name: evergreen
  version: 1.0.0

source:
   url: https://github.com/KolluriSatya/coding_practice/tree/evergreen

build:
  number: 0
  noarch: python
  script: conda env create -f evergreen.yaml

requirements:
  host:
    - wget
    - python=2.7
    - pip
    - scipy
    - numpy=1.15
    - ete3
    - joblib
    - kma=1.4.9
  run:
    - wget
    - python=2.7
    - pip
    - scipy
    - numpy=1.15
    - ete3
    - cgecore
    - tabulate
    - blast
    - joblib
    - kma=1.4.9

about:
  home: https://github.com/KolluriSatya/coding_practice/tree/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0