package:
  name: plasmidfinder
  version: 2.1.6

source:
  url: https://bitbucket.org/genomicepidemiology/plasmidfinder/get/2.1.6.tar.gz

build:
  number: 1

requirements:
  host:
    - python >=3
    - kma
    - wget
  run:
    - python >=3
    - kma
    - biopython
    - tabulate
    - cgecore
    - blast

test:
  imports:
    - click
  requires:
    - pip
  commands:
    - plasmidfinder.py -h | grep plasmidfinder.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/plasmidfinder
  license: Apache-2.0
  summary: "PlasmidFinder allows identification of plasmids in total or partial sequenced isolates of bacteria."

extra:
  identifiers:
    - doi:10.1128/AAC.02412-14