package:
  name: evergreen
  version: 3.8.3

source:
   url: https://github.com/Kollurisatya/coding_practice/archive/refs/tags/v3.8.3.tar.gz

build:
  number: 0
  noarch: python

requirements:
  host:
    - wget
    - python=2.7
    - kma=1.4.9
    - numpy=1.15
    - scipy
    - joblib
  run:
    - wget
    - python=2.7
    - kma=1.4.9
    - numpy=1.15
    - joblib
about:
  home: https://github.com/KolluriSatya/coding_practice/tree/evergreen
  summary: 'The Evergreen SNP phylogenic pipeline is for the purpose of continuous phylogenetical analysis of bacterial whole-genome sequencing data.'
  license: Apache-2.0