package:
  name: mintyper
  version: 0.1.0

source:
  url: https://github.com/genomicepidemiology/mintyper/get/v0.1.0.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.6
    - pip
    - kma >=1.4.9
    - ccphylo >=0.8.2
  run:
    - python >=3.6
    - kma >=1.4.9
    - ccphylo >=0.8.2
about:
  home: https://github.com/genomicepidemiology/mintyper
  summary: 'mintyper test.'
  license: Apache-2.0