package:
  name: flankophile
  version: 0.2.8

source:
  url: https://github.com/KolluriSatya/coding_practice/tree/flankophile

build:
  number: 0

requirements:
  host:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6
  run:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6
test:
  commands:
    snakemake -h

about:
  home: https://bitbucket.org/genomicepidemiology/flankophile
  summary: 'flankophile test.'
  license: Apache-2.0