import yaml
import os
import sys

sys.path = [os.path.join(os.path.dirname(os.path.realpath(__file__)), '')] + sys.path

import src.resfinder.version as version

    data = {
"package": {
    "name": "resfinder",
    "version": version.__version__
},
"source": {
    "url": "https://files.pythonhosted.org/packages/ce/9c/f87f17e82b6666e3d3214cdf2970e46585108b5821ef80d2d58bf4470e86/resfinder-4.3.3.tar.gz",
    "sha256": "9b45c520ae8e29a7035665959b9250e6a8c2d43b389d3da8299b6d493d14d9b7"
},
"build": {
    "number": 0,
    "noarch": "python",


    package:
    name: cgecore
    version: 1.5.6
source:
    url: https://files.pythonhosted.org/packages/24/f0/f4507b608865e56757f80000c34405c8a43e973e888e11e6bdc18fe47ce1/cgecore-1.5.6.tar.gz
build:
    noarch: python
    number: '0'
    script: /opt/conda/conda-bld/cgecore_1604319091913/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed -vv
    string: pyh3252c3a_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h924ce5b_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.4 py_0
        - python 3.8.6 h852b56e_0_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h924ce5b_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - biopython
        - python
test:
    imports:
        - cgecore
        - cgecore.alignment
        - cgecore.argumentparsing
        - cgecore.blaster
        - cgecore.cgefinder
        - cgecore.cmdline
        - cgecore.organisminfo
        - cgecore.utility
about:
    dev_url: https://bitbucket.org/genomicepidemiology/cge_core_module
    home: https://bitbucket.org/genomicepidemiology/cge_core_module
    license: Apache-2.0
    license_family: Apache
    summary: Center for Genomic Epidemiology Core Module
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - npavlovikj
