package:
  name: Mintyper
  version: 0.0.3

source:
  url: https://bitbucket.org/genomicepidemiology/mintyper/archive/refs/tags/v1.0.11.tar.gz

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.9
    - pip
    - kma >=1.4.9
    - ccphylo >=0.8.2
  run:
    - python >=3.9
    - pip
    - kma>=1.4.9
    - ccphylo >=0.8.2
about:
  home: https://bitbucket.org/genomicepidemiology/mintyper
  summary: 'Mintyper is a tool designed to quickly estimate a distance matrix from a set of input sequencing reads. It can take both short read from Illumina's sequencing platforms and long reads from Oxford Nanopore's platform.'
  license: Apache-2.0
extra:
  identifiers:
    - doi:10.1093/biomethods/bpab008: