package:
  name: plasmidfinder
  version: 2.1.6

source:
  url: https://github.com/genomicepidemiology/plasmidfinder/releases/tags/v2.1.6

build:
  number: 1
  noarch: generic

requirements:
  host:
    - python>=3.5
    - kma
    - wget
run:
    - python>=3.5
    - kma
    - biopython
    - tabulate
    - cgecore
    - blast
test:
  commands:
    - plasmidfinder.py -h | grep plasmidfinder.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/plasmidfinder
  license: Apache-2.0
  summary: "PlasmidFinder service"