package:
  name: flankophile
  version: 3.6.5

source:
  url: https://github.com/KolluriSatya/coding_practice/archive/refs/v3.6.5.tar.gz

build:
  number: 0
  noarch: generic
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6
  run:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - kma=1.4.0
    - prokka=1.14.6

about:
  home: https://bitbucket.org/genomicepidemiology/flankophile
  summary: 'flankophile test.'
  license: Apache-2.0