package:
  name: flankophile
  version: 3.8.9

source:
  url: https://github.com/KolluriSatya/coding_practice/archive/refs/v3.8.9.tar.gz

build:
  number: 0
  noarch: generic
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - tabulate=0.8.10
    - kma=1.4.0
  run:
    - wget
    - python=3.7
    - snakemake=6.9.1
    - tabulate=0.8.10
    - kma=1.4.0
about:
  home: https://bitbucket.org/genomicepidemiology/flankophile
  summary: 'flankophile test.'
  license: Apache-2.0