name: conda-linux-release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  auto-tag-release:
    name: convert_to_tar_file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
  conda-linux:
    name: Linux Upload
    runs-on: ubuntu-latest
    needs: convert_to_tar_file
    steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: BEFH/anaconda-publish@v1.5.1
        with:
          subDir: 'conda'
          channels: 'conda-forge -c bioconda -c defaults'
          AnacondaToken: ${{ secrets.SATYA_CONDA_AUTH_TOKEN }}
          publish: true
