name: conda-osx-release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  conda-osx:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          installer_url: https://github.com/KolluriSatya/coding_practice/tree/evergreen
          channels: conda-forge,bioconda,defaults
          auto-update-conda: true
          show-channel-urls: true
          auto-activate-base: true
          use-only-tar-bz2: false

      - name: update mamba
        run: |
          conda info
          conda list 
          conda config --show-sources
          conda config --show

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.SATYA_CONDA_AUTH_TOKEN }}
