on:
  workflow_dispatch

name: manual release linux

jobs:
  conda-linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          python conda/make_conda.py

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml

      - name: build conda package
        run: |
          conda mambabuild conda -c conda-forge -c genomicepidemiology -c bioconda --output-folder .

      - name: Get latest commit tag
        id: get_tag
        run: |
            COMMIT_TAG=$(git describe --tags --abbrev=0)
            echo "::set-output name=tag::$COMMIT_TAG"

      - name: Create source package with commit tag
        run: |
            TAG=$(echo ${{ steps.get_tag.outputs.tag }})

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.SATYA_CONDA_AUTH_TOKEN }} upload --label main noarch/*.tar.bz2