on:
  workflow_dispatch

name: manual release linux

jobs:
  conda-linux:
    name: Linux Upload
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
            pip install PyYAML
            pip install ruamel.yaml
            python conda/make_conda_linux.py
            cat conda/meta.yaml

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml

      - name: publish-to-conda
        uses: paskino/conda-package-publish-action@master
        with:
          subDir: 'conda'
          channels: 'genomicepidemiology -c bioconda -c conda-forge'
          AnacondaToken: ${{ secrets.SATYA_CONDA_AUTH_TOKEN }}
          publish: true