on:
  workflow_dispatch:
    name: conda_release
jobs:
  conda-release:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Make conda yaml
        run: |
            pip install PyYAML
            pip install ruamel.yaml
            python conda/make_conda_linux.py
            cat conda/meta.yaml
        uses: BEFH/anaconda-publish@v1.5.1
        with:
          subDir: 'conda'
          channels: 'conda-forge -c bioconda -c defaults'
          AnacondaToken: ${{ secrets.SATYA_CONDA_AUTH_TOKEN }}
          publish: true
