on:
  workflow_dispatch

name: manual release linux

jobs:
  conda-linux:
    name: Linux Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make conda yaml
        run: |
          pip install PyYAML
          pip install ruamel.yaml
          python conda/make_conda.py
          cat conda/meta.yaml
      - name: build conda package
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml   
      
      - name: build package
        run: |
          conda mambabuild conda -c conda-forge -c genomicepidemiology --output-folder .

      - name: upload conda package
        run: |
          
          anaconda -t ${{ secrets.SATYA_CONDA_AUTH_TOKEN }} upload --label main osx-64/*.tar.bz2
