on:
  workflow_dispatch

name: manual release linux

jobs:
  conda-linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          pip install ruamel.yaml
          python conda/make_conda.py
          cat conda/meta.yaml
          

      - name: build conda package
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          activate-environment: linux-build
          environment-file: envs/linux-build.yml

      - name: check solution
        run: |
          mamba env export

      - name: build conda package
        run: |
          conda mambabuild conda -c conda-forge --output-folder .

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.SATYA_CONDA_AUTH_TOKEN }} upload --label main linux-64/*.tar.bz2
