on:
  workflow_dispatch:

jobs:
  conda-noarch:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          pip install ruamel.yaml
          python make_conda_linux.py
          cat conda/meta.yaml.template

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml

      - name: build conda package
        run: |
          conda mambabuild conda -c conda-forge --output-folder .
          
          - name: upload conda package
          run: |
          anaconda -t ${{ secrets.SATYA_CONDA_AUTH_TOKEN }} upload --label main cgecore-1.5.6.tar.gz
